import Footer from '@/components/Footer'
import NodejsIcon from '@/components/NodejsIcon'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function chartsLayout ({ children }) {
  return (
    <html lang='en'>
      <body className='flex flex-col items-center justify-center w-full'>
        <h1 className='gap-2 text-center text-5xl font-bold text-[#8CC84B] pt-6 md:text-6xl lg:text-8xl md:flex md:justify-center md:items-center'>
          Downloads Node.js
          <span className='flex items-center justify-center pt-2'>
            <NodejsIcon />
          </span>
        </h1>
        {children}
        <Footer />
      </body>
    </html>
  )
}
