import './globals.css'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import InfoUpdate from '@/components/InfoUpdate'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html
      lang='en'
    >
      <body>
        <Header />
        <InfoUpdate />
        {children}
        <Footer />
      </body>
    </html>
  )
}
