import Footer from '@/components/Footer'
import NodejsIcon from '@/components/NodejsIcon'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className='flex flex-col items-center justify-center w-full'>
        <h1 className='flex items-center justify-center gap-2 text-[#8CC84B] font-medium text-6xl pt-8'>
          Nodejs Compare
          <NodejsIcon />
        </h1>
        {children}
        <Footer />
      </body>
    </html>
  )
}
